### ISSUE TITLE
WXPayConfig 不能在其他包下面继承

### ISSUE THREAD

**Issue by chiyanking** [TedZhDZ/wxpay-sdk#2]
我pom中引入后发现不能继承

**Comment by chiyanking** [comment]
![image](https://user-images.githubusercontent.com/14103943/43447064-263f426a-94dd-11e8-9757-1b5c2512d28d.png)

**Comment by chiyanking** [comment]
是否可以改成
![image](https://user-images.githubusercontent.com/14103943/43447121-536da95c-94dd-11e8-97e3-622827a94dae.png)

**Comment by TedZhDZ** [comment]
谢谢你的建议，我也发现了这个问题，稍后修正后提交

**Comment by TedZhDZ** [comment]
代码我已经更新提交了，主要更改是：将WXPayConfig类中的抽象方法加上protected修饰
